# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, async
, base
, bilge
, bytestring
, bytestring-conversion
, cassandra-util
, containers
, cql
, currency-codes
, data-default
, errors
, exceptions
, extended
, gitignoreSource
, gundeck-types
, hspec
, hspec-discover
, http-client
, http-types
, http2-manager
, imports
, iso639
, lens
, lib
, polysemy
, polysemy-plugin
, polysemy-wire-zoo
, QuickCheck
, quickcheck-instances
, retry
, servant
, servant-client-core
, string-conversions
, text
, tinylog
, transformers
, transitive-anns
, types-common
, wai-utilities
, wire-api
, wire-api-federation
}:
mkDerivation {
  pname = "wire-subsystems";
  version = "0.1.0";
  src = gitignoreSource ./.;
  libraryHaskellDepends = [
    aeson
    async
    base
    bilge
    bytestring
    bytestring-conversion
    cassandra-util
    containers
    cql
    currency-codes
    errors
    exceptions
    extended
    gundeck-types
    http-client
    http-types
    http2-manager
    imports
    lens
    polysemy
    polysemy-plugin
    polysemy-wire-zoo
    QuickCheck
    retry
    servant
    servant-client-core
    text
    tinylog
    transformers
    transitive-anns
    types-common
    wai-utilities
    wire-api
    wire-api-federation
  ];
  testHaskellDepends = [
    aeson
    async
    base
    bilge
    bytestring
    containers
    data-default
    extended
    gundeck-types
    hspec
    imports
    iso639
    polysemy
    polysemy-plugin
    polysemy-wire-zoo
    QuickCheck
    quickcheck-instances
    servant-client-core
    string-conversions
    transformers
    types-common
    wire-api
    wire-api-federation
  ];
  testToolDepends = [ hspec-discover ];
  license = lib.licenses.agpl3Only;
}
