apiVersion: v1
description: A Helm chart for wire-server https://github.com/wireapp/wire-server
name: wire-server
version: 0.0.42
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - name: background-worker
      image: quay.io/wire/background-worker:do-not-use
    - name: brig
      image: quay.io/wire/brig:do-not-use
    - name: brig-integration
      image: quay.io/wire/brig-integration:do-not-use
    - name: cannon
      image: quay.io/wire/cannon:do-not-use
    - name: cannon-configurator
      image: docker.io/library/alpine:3.24.1
    - name: cargohold
      image: quay.io/wire/cargohold:do-not-use
    - name: cargohold-integration
      image: quay.io/wire/cargohold-integration:do-not-use
    - name: galley
      image: quay.io/wire/galley:do-not-use
    - name: galley-integration
      image: quay.io/wire/galley-integration:do-not-use
    - name: gundeck
      image: quay.io/wire/gundeck:do-not-use
    - name: gundeck-integration
      image: quay.io/wire/gundeck-integration:do-not-use
    - name: nginz
      image: quay.io/wire/nginz:do-not-use
    - name: spar
      image: quay.io/wire/spar:do-not-use
    - name: spar-integration
      image: quay.io/wire/spar-integration:do-not-use
