dependencies:
########################
## wire-servers/database cassandra-migrations
########################
- name: cassandra-migrations
  version: "0.0.42"
  repository: "file://../cassandra-migrations"
  tags:
    - cassandra-migrations
- name: elasticsearch-index
  version: "0.0.42"
  repository: "file://../elasticsearch-index"
  tags:
    - elasticsearch-index
########################
## wire-servers/services
########################
- name: backoffice
  version: "0.0.42"
  repository: "file://../backoffice"
  tags:
    - backoffice
    - haskellServices
    - services
- name: spar
  version: "0.0.42"
  repository: "file://../spar"
  tags:
    - spar
    - haskellServices
    - services
- name: nginz
  version: "0.0.42"
  repository: "file://../nginz"
  tags:
    - nginz
    - services
- name: legalhold
  version: "0.0.42"
  repository: "file://../legalhold"
  tags:
    - legalhold
    - private
- name: federator
  version: "0.0.42"
  repository: "file://../federator"
  tags:
    - federator
    - federation
    - haskellServices
    - services
- name: integration
  version: "0.0.42"
  repository: "file://../integration"
  tags:
    - integration
- name: mlsstats
  version: "0.0.42"
  repository: "file://../mlsstats"
  tags:
    - mlsstats
