# Default values for wire-server.

# Tags allow to enable/disable certain components of wire-server as defined in requirements.yaml
# https://docs.helm.sh/developing_charts/#tags-and-condition-fields-in-requirements-yaml
# tags:
#   services: true

tags:
  legalhold: false
  federation: false # keep in sync with global.enableFederation
  backoffice: false
  mlsstats: false
  integration: false

global:
  enableFederation: false
  federationDomain: ""
