{{- if .Values.websockets.enabled }}
{{/* Disable the idle timeout for long-lived WebSockets. */}}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ include "wire-ingress.fullname" . }}-nginz-websockets
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  targetRefs:
    {{- range $domain := include "wire-ingress.domains" . | fromJsonArray }}
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ include "wire-ingress.fullname" $ }}-nginz-websockets{{ $domain.suffix }}
    {{- end }}
  {{- if .Values.gateway.zoneAwareRouting.enabled }}
  mergeType: StrategicMerge
  {{- end }}
  timeout:
    http:
      streamIdleTimeout: "0s"
{{- end }}
