{{- if .Values.tls.useCertManager -}}
{{- $root := . -}}
{{- $domains := include "wire-ingress.domains" . | fromJsonArray -}}
{{- range $domain := $domains }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $domain.certName }}"
  namespace: {{ $root.Release.Namespace }}
  labels:
    chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
    release: "{{ $root.Release.Name }}"
    heritage: "{{ $root.Release.Service }}"
spec:
  issuerRef:
    name: {{ $domain.issuerName | quote }}
    kind: {{ $domain.issuerKind }}
  usages:
    - server auth
  duration: 2160h     # 90d, Letsencrypt default; NOTE: changes are ignored by Letsencrypt
  renewBefore: 360h   # 15d
  isCA: false
  secretName: {{ $domain.secretName | quote }}

  privateKey:
    algorithm: {{ $root.Values.tls.privateKey.algorithm }}
    size: {{ $root.Values.tls.privateKey.size }}
    encoding: PKCS1
    rotationPolicy: {{ $root.Values.tls.privateKey.rotationPolicy }}

  dnsNames:
    - {{ $domain.https }}
    {{- if and $root.Values.websockets.enabled $domain.ssl }}
    - {{ $domain.ssl }}
    {{- end }}
    {{- if and $root.Values.webapp.enabled $domain.webapp }}
    - {{ $domain.webapp }}
    {{- end }}
    {{- if and $root.Values.fakeS3.enabled $domain.fakeS3 }}
    - {{ $domain.fakeS3 }}
    {{- end }}
    {{- if and $root.Values.teamSettings.enabled $domain.teamSettings }}
    - {{ $domain.teamSettings }}
    {{- end }}
    {{- if and $root.Values.accountPages.enabled $domain.accountPages }}
    - {{ $domain.accountPages }}
    {{- end }}
{{- end }}
{{- end -}}
