{{- if .Values.webapp.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "wire-ingress.fullname" . }}-webapp
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  parentRefs:
    - name: {{ include "wire-ingress.getGatewayName" . | quote }}
      namespace: {{ .Release.Namespace | quote }}
      kind: Gateway
      sectionName: https
  hostnames:
    - {{ required "config.dns.webapp is required when webapp.enabled is true" .Values.config.dns.webapp | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: webapp-http
          port: {{ .Values.service.webapp.externalPort }}
          kind: Service
{{- end }}
