{{- $root := . -}}
{{- $domains := include "wire-ingress.domains" . | fromJsonArray -}}
{{- range $domain := $domains }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "wire-ingress.fullname" . }}-nginz
  namespace: {{ .Release.Namespace }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
    release: "{{ $root.Release.Name }}"
    heritage: "{{ $root.Release.Service }}"
spec:
  parentRefs:
    - name: {{ include "wire-ingress.gatewayName" $root | quote }}
      namespace: {{ $root.Release.Namespace | quote }}
      kind: Gateway
      sectionName: {{ $domain.section }}
  hostnames:
    - {{ required "config.dns.https is required" $domain.https | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nginz
          port: {{ $root.Values.service.nginz.httpPort }}
          kind: Service
{{- end }}
