{{- if and (not .Values.tls.useCertManager) .Values.tls.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wire-ingress.getCertificateSecretName" . | quote }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/tls
data:
  {{- with .Values.secrets }}
  tls.crt: {{ .tlsWildcardCert | b64enc | quote }}
  tls.key: {{ .tlsWildcardKey | b64enc | quote }}
  {{- end -}}
{{- end -}}
