{{- if .Values.accountPages.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: account-pages-http
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.accountPages.externalPort }}
      targetPort: 8080
  selector:
    app: account-pages
{{- end }}
