{{- if .Values.teamSettings.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: team-settings-http
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.teamSettings.externalPort }}
      targetPort: 8080
  selector:
    app: team-settings
{{- end }}
