{{- if .Values.accountPages.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: account-pages-http
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.accountPages.externalPort }}
      targetPort: 8080
  selector:
    app: account-pages
{{- end }}
