fullnameOverride: fake-aws-s3

image:
  repository: rustfs/rustfs
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 9000

credentials:
  accessKey: dummykey
  secretKey: dummysecret

storage:
  dataPath: /data

resources:
  requests:
    memory: 200Mi

bootstrap:
  image:
    repository: amazon/aws-cli
    tag: 2.17.49
    pullPolicy: IfNotPresent
  buckets:
    - name: dummy-bucket
    - name: assets
    - name: public
