# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, base
, bytestring
, bytestring-conversion
, containers
, crypton
, errors
, gitignoreSource
, http-types
, imports
, lib
, memory
, text
, types-common
, uuid
, wai-utilities
, wire-api
}:
mkDerivation {
  pname = "galley-types";
  version = "0.81.0";
  src = gitignoreSource ./.;
  libraryHaskellDepends = [
    aeson
    base
    bytestring
    bytestring-conversion
    containers
    crypton
    errors
    http-types
    imports
    memory
    text
    types-common
    uuid
    wai-utilities
    wire-api
  ];
  license = lib.licenses.agpl3Only;
}
