# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, base
, bytestring
, containers
, gitignoreSource
, imports
, lib
, monoidal-containers
, optparse-generic
, postgresql-simple
, prettyprinter
, prometheus-client
, text
, xml
}:
mkDerivation {
  pname = "test-stats";
  version = "0.1.0";
  src = gitignoreSource ./.;
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    base
    bytestring
    containers
    imports
    monoidal-containers
    optparse-generic
    postgresql-simple
    prettyprinter
    prometheus-client
    text
    xml
  ];
  description = "Test run statistics";
  license = lib.licenses.agpl3Only;
  mainProgram = "test-stats";
}
