# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation, base, cassandra-util, gitignoreSource, HsOpenSSL
, hspec, imports, lib, polysemy, polysemy-check, polysemy-plugin
, QuickCheck, saml2-web-sso, time, tinylog, types-common, uuid
, wire-api
}:
mkDerivation {
  pname = "polysemy-wire-zoo";
  version = "0.1.0";
  src = gitignoreSource ./.;
  libraryHaskellDepends = [
    base cassandra-util HsOpenSSL hspec imports polysemy polysemy-check
    polysemy-plugin QuickCheck saml2-web-sso time tinylog types-common
    uuid wire-api
  ];
  description = "Polysemy interface for various libraries";
  license = lib.licenses.agpl3Only;
}
