apiVersion: v1
description: A Helm chart for cannon in Kubernetes
name: cannon
version: 0.0.42
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - name: cannon
      image: quay.io/wire/cannon:do-not-use
    - name: nginz
      image: quay.io/wire/nginz:do-not-use
    - name: alpine
      image: docker.io/library/alpine:3.21.3
