# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, amqp
, async
, base
, bilge
, bytestring
, bytestring-conversion
, exceptions
, extended
, federator
, gitignoreSource
, HsOpenSSL
, hspec
, http-client
, http-types
, http2-manager
, imports
, lens
, lib
, monad-control
, optparse-applicative
, QuickCheck
, retry
, tagged
, tasty
, tasty-hunit
, text
, tinylog
, transformers-base
, types-common
, wire-api
, wire-api-federation
, yaml
}:
mkDerivation {
  pname = "background-worker";
  version = "0.1.0.0";
  src = gitignoreSource ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson
    amqp
    async
    base
    bilge
    bytestring
    bytestring-conversion
    exceptions
    extended
    HsOpenSSL
    http-client
    http-types
    http2-manager
    imports
    lens
    monad-control
    retry
    text
    tinylog
    transformers-base
    types-common
    wire-api
    wire-api-federation
  ];
  executableHaskellDepends = [
    aeson
    amqp
    async
    base
    exceptions
    federator
    HsOpenSSL
    hspec
    imports
    optparse-applicative
    QuickCheck
    tagged
    tasty
    tasty-hunit
    types-common
    wire-api
    wire-api-federation
    yaml
  ];
  testHaskellDepends = [
    aeson
    amqp
    async
    base
    exceptions
    federator
    HsOpenSSL
    hspec
    imports
    optparse-applicative
    QuickCheck
    tagged
    tasty
    tasty-hunit
    types-common
    wire-api
    wire-api-federation
    yaml
  ];
  description = "Runs background work";
  license = lib.licenses.agpl3Only;
}
