# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, amqp
, base
, gitignoreSource
, HsOpenSSL
, http2-manager
, imports
, lib
, text
, types-common
, wire-api-federation
}:
mkDerivation {
  pname = "background-worker";
  version = "0.1.0.0";
  src = gitignoreSource ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson
    amqp
    base
    HsOpenSSL
    http2-manager
    imports
    text
    types-common
    wire-api-federation
  ];
  executableHaskellDepends = [ HsOpenSSL imports types-common ];
  testHaskellDepends = [ imports ];
  description = "Runs background work";
  license = lib.licenses.agpl3Only;
  mainProgram = "background-worker";
}
