{{- if .Values.secrets.awsKeyId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: mlsstats
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  awsKeyId: {{ .Values.secrets.awsKeyId | b64enc | quote }}
  awsSecretKey: {{ .Values.secrets.awsSecretKey | b64enc | quote }}
{{- end }}
