#!/usr/bin/env bash
set -e

exec 2>&1

# defaults
USER=${USER:=www-data}
APP=gundeck
CONFIG=${CONFIG:=/etc/${APP}/${APP}.yaml}
HOME=${APP_HOME:=/opt/$APP}
BIN=$HOME/bin/$APP

chpst -u $USER get_config

export LOG_LEVEL=${GUNDECK_LOG_LEVEL:-Debug}
export LOG_BUFFER=${GUNDECK_LOG_BUFFER:-4096}
export LOG_NETSTR=${GUNDECK_LOG_NETSTR:-True}

cd $HOME

ulimit -n 65536

exec chpst -u $USER $BIN --config-file=${CONFIG}
