# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation, aeson, amazonka, amazonka-s3, base
, base64-bytestring, bytestring, cassandra-util, conduit, filepath
, gitignoreSource, http-types, imports, lens, lib
, optparse-applicative, schema-profunctor, text, time, tinylog
, types-common, wire-api
}:
mkDerivation {
  pname = "mlsstats";
  version = "0.1.0";
  src = gitignoreSource ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson amazonka amazonka-s3 base base64-bytestring bytestring
    cassandra-util conduit filepath http-types imports lens
    optparse-applicative schema-profunctor text time tinylog
    types-common wire-api
  ];
  executableHaskellDepends = [ base imports optparse-applicative ];
  license = lib.licenses.agpl3Only;
  mainProgram = "mlsstats";
}
