# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, aeson-pretty
, amqp
, async
, base
, bytestring
, bytestring-conversion
, containers
, exceptions
, gitignoreSource
, HsOpenSSL
, hspec
, hspec-discover
, http-media
, http-types
, http2
, http2-manager
, HUnit
, imports
, kan-extensions
, lens
, lib
, metrics-wai
, mtl
, QuickCheck
, schema-profunctor
, servant
, servant-client
, servant-client-core
, servant-server
, singletons
, singletons-th
, swagger2
, text
, time
, transformers
, types-common
, uuid
, wai-utilities
, wire-api
}:
mkDerivation {
  pname = "wire-api-federation";
  version = "0.1.0";
  src = gitignoreSource ./.;
  libraryHaskellDepends = [
    aeson
    amqp
    async
    base
    bytestring
    bytestring-conversion
    containers
    exceptions
    HsOpenSSL
    http-media
    http-types
    http2
    http2-manager
    imports
    kan-extensions
    lens
    metrics-wai
    mtl
    QuickCheck
    schema-profunctor
    servant
    servant-client
    servant-client-core
    servant-server
    singletons-th
    swagger2
    text
    time
    transformers
    types-common
    wai-utilities
    wire-api
  ];
  testHaskellDepends = [
    aeson
    aeson-pretty
    base
    bytestring
    containers
    hspec
    HUnit
    imports
    QuickCheck
    singletons
    types-common
    uuid
    wire-api
  ];
  testToolDepends = [ hspec-discover ];
  description = "The Wire server-to-server API for federation";
  license = lib.licenses.agpl3Only;
}
