apiVersion: v1
description: Spar (part of Wire Server) - SSO Service
name: spar
version: 0.0.42
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - name: spar
      image: quay.io/wire/spar:do-not-use
