-- This file is part of the Wire Server implementation.
--
-- Copyright (C) 2026 Wire Swiss GmbH <opensource@wire.com>
--
-- This program is free software: you can redistribute it and/or modify it under
-- the terms of the GNU Affero General Public License as published by the Free
-- Software Foundation, either version 3 of the License, or (at your option) any
-- later version.
--
-- This program is distributed in the hope that it will be useful, but WITHOUT
-- ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
-- FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
-- details.
--
-- You should have received a copy of the GNU Affero General Public License along
-- with this program. If not, see <https://www.gnu.org/licenses/>.

-- Prefix-search index for name_normalized (LIKE 'abc%', no pg_trgm needed);
-- companion to 20260911000000-user-search-postgres.sql.  Runs outside a
-- transaction (CREATE INDEX CONCURRENTLY); see
-- 'Wire.PostgresMigrations.nonTransactionMigrations'.  One statement per file:
-- statements within a single script run in one implicit transaction, which
-- CREATE INDEX CONCURRENTLY forbids.
CREATE INDEX CONCURRENTLY IF NOT EXISTS wire_user_name_normalized_pattern_idx ON wire_user (name_normalized text_pattern_ops);
