{{- if .Values.cargohold.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cargohold.serviceAccount.name }}
  labels:
    app: cargohold
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.cargohold.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.cargohold.serviceAccount.automountServiceAccountToken }}
{{- end }}
