apiVersion: v1
description: Elasticsearch index for brig
name: elasticsearch-index
version: 0.0.42
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - name: brig-index
      image: quay.io/wire/brig-index:do-not-use
