apiVersion: v1
description: Backoffice tool
name: backoffice
version: 0.0.42
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - name: stern
      image: quay.io/wire/stern:do-not-use
