apiVersion: v1
description: A Helm chart for nginz in Kubernetes
name: nginz
version: 0.0.42
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - name: nginz
      image: quay.io/wire/nginz:do-not-use
    - name: nginz-disco
      image: quay.io/wire/nginz_disco:do-not-use
