# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, base
, bytestring
, containers
, criterion
, double-conversion
, fast-logger
, gitignoreSource
, lib
, text
, transformers
, unix-time
}:
mkDerivation {
  pname = "tinylog";
  version = "0.15.0";
  src = gitignoreSource ./.;
  libraryHaskellDepends = [
    base
    bytestring
    containers
    double-conversion
    fast-logger
    text
    transformers
    unix-time
  ];
  benchmarkHaskellDepends = [ base bytestring criterion ];
  homepage = "https://gitlab.com/twittner/tinylog/";
  description = "Simplistic logging using fast-logger";
  license = lib.licenses.mpl20;
}
