apiVersion: v1
description: Backend notification pusher
name: background-worker
version: 0.0.42
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - name: background-worker
      image: quay.io/wire/background-worker:do-not-use
