apiVersion: v1
description: Cargohold (part of Wire Server) - Asset storage
name: cargohold
version: 0.0.42
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - name: cargohold
      image: quay.io/wire/cargohold:do-not-use
