# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation, base, Cabal, gitignoreSource, lib
, proto-lens-protoc, proto-lens-runtime, proto-lens-setup
}:
mkDerivation {
  pname = "wire-message-proto-lens";
  version = "0.1.0";
  src = gitignoreSource ./.;
  setupHaskellDepends = [ base Cabal proto-lens-setup ];
  libraryHaskellDepends = [ base proto-lens-runtime ];
  libraryToolDepends = [ proto-lens-protoc ];
  description = "Shared protobuf type definitions for Wire Messaging";
  license = lib.licenses.agpl3Only;
}
