# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, aeson-pretty
, base
, bytestring
, containers
, envparse
, gitignoreSource
, http-client
, http-client-tls
, http-types
, imports
, lib
, optparse-applicative
, tasty
, tasty-golden
, tasty-hunit
, text
, types-common
, uuid
}:
mkDerivation {
  pname = "entreprise-provisioning";
  version = "0.1.0";
  src = gitignoreSource ./.;
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    aeson
    base
    bytestring
    containers
    envparse
    http-client
    http-client-tls
    http-types
    imports
    optparse-applicative
    text
    types-common
    uuid
  ];
  testHaskellDepends = [
    aeson
    aeson-pretty
    base
    bytestring
    containers
    imports
    tasty
    tasty-golden
    tasty-hunit
    types-common
  ];
  description = "CLI tool for provisioning user groups with channels";
  license = lib.licenses.agpl3Only;
  mainProgram = "entreprise-provisioning";
}
