apiVersion: v1
description: Proxy (part of Wire Server) - 3rd party proxy service
name: proxy
version: 0.0.42
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - name: proxy
      image: quay.io/wire/proxy:do-not-use
