{{- if not .Values.envoy.enabled }}
{{- $newLabels := eq (include "integrationTestHelperNewLabels" .) "true" -}}
{{- range $name, $dynamicBackend := .Values.config.dynamicBackends }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: integration-federator-{{ $name }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "{{ $.Values.tls.verify_depth }}"
    nginx.ingress.kubernetes.io/auth-tls-secret: "{{ or $.Values.tls.caNamespace $.Release.Namespace }}/federator-ca-secret"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header "X-SSL-Certificate" $ssl_client_escaped_cert;
spec:
  ingressClassName: "{{ $.Values.ingress.class }}"
  tls:
  - hosts:
      - {{ $dynamicBackend.federatorExternalHostPrefix }}.{{ $.Release.Namespace }}.svc.cluster.local
    secretName: federator-certificate-secret
  rules:
    - host: {{ $dynamicBackend.federatorExternalHostPrefix }}.{{ $.Release.Namespace }}.svc.cluster.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: integration
                port:
                  number: {{ $dynamicBackend.federatorExternalPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $dynamicBackend.federatorExternalHostPrefix }}
spec:
  ports:
  - name: wire-server-federator
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    {{- if $newLabels }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: ingress-nginx
    {{- else }}
    app: nginx-ingress
    component: controller
    {{- end }}
  type: ClusterIP
{{- end }}
{{- end }}
