# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation, base, bytestring, Cabal, gitignoreSource, imports
, lib, proto-lens-protoc, proto-lens-runtime, proto-lens-setup
, time, types-common, uuid
}:
mkDerivation {
  pname = "types-common-journal";
  version = "0.1.0";
  src = gitignoreSource ./.;
  setupHaskellDepends = [ base Cabal proto-lens-setup ];
  libraryHaskellDepends = [
    base bytestring imports proto-lens-runtime time types-common uuid
  ];
  libraryToolDepends = [ proto-lens-protoc ];
  description = "Shared protobuf type definitions";
  license = lib.licenses.agpl3Only;
}
