# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, base
, base64-bytestring
, binary
, bytestring
, case-insensitive
, containers
, cookie
, crypton
, crypton-asn1-encoding
, crypton-asn1-parse
, crypton-asn1-types
, crypton-x509
, data-default
, directory
, dns
, email-validate
, errors
, exceptions
, extra
, file-path-th
, filepath
, foundation
, ghc-prim
, hedgehog
, hedgehog-quickcheck
, hsaml2
, hspec
, hspec-core
, hspec-discover
, hspec-wai
, http-media
, http-types
, hxt
, hxt-regex-xmlschema
, imports
, invertible-hxt
, lens
, lens-datetime
, lib
, mtl
, network-uri
, openapi3
, pretty-show
, process
, QuickCheck
, quickcheck-instances
, ram
, random
, schema-profunctor
, servant
, servant-multipart
, servant-server
, shelly
, silently
, string-conversions
, temporary
, text
, time
, time-hourglass
, tinylog
, transformers
, types-common
, uniplate
, uri-bytestring
, utf8-string
, uuid
, wai
, wai-extra
, wai-utilities
, warp
, word8
, xml-conduit
, xml-conduit-writer
, xml-hamlet
, xml-types
, yaml
}:
mkDerivation {
  pname = "saml2-web-sso";
  version = "0.20";
  src = ./.;
  libraryHaskellDepends = [
    aeson
    base
    base64-bytestring
    binary
    bytestring
    case-insensitive
    containers
    cookie
    crypton
    crypton-asn1-encoding
    crypton-asn1-parse
    crypton-asn1-types
    crypton-x509
    data-default
    directory
    dns
    email-validate
    errors
    exceptions
    extra
    file-path-th
    filepath
    foundation
    ghc-prim
    hedgehog
    hedgehog-quickcheck
    hsaml2
    hspec
    hspec-wai
    http-media
    http-types
    hxt
    hxt-regex-xmlschema
    imports
    invertible-hxt
    lens
    lens-datetime
    mtl
    network-uri
    openapi3
    pretty-show
    process
    QuickCheck
    quickcheck-instances
    ram
    random
    schema-profunctor
    servant
    servant-multipart
    servant-server
    shelly
    silently
    string-conversions
    temporary
    text
    time
    time-hourglass
    tinylog
    transformers
    types-common
    uniplate
    uri-bytestring
    utf8-string
    uuid
    wai
    wai-extra
    wai-utilities
    warp
    word8
    xml-conduit
    xml-conduit-writer
    xml-hamlet
    xml-types
    yaml
  ];
  testHaskellDepends = [
    aeson
    base
    base64-bytestring
    binary
    bytestring
    case-insensitive
    containers
    cookie
    crypton
    crypton-asn1-encoding
    crypton-asn1-parse
    crypton-asn1-types
    crypton-x509
    data-default
    directory
    dns
    email-validate
    errors
    exceptions
    extra
    filepath
    foundation
    ghc-prim
    hedgehog
    hedgehog-quickcheck
    hsaml2
    hspec
    hspec-core
    hspec-discover
    hspec-wai
    http-media
    http-types
    hxt
    imports
    lens
    lens-datetime
    mtl
    network-uri
    pretty-show
    process
    QuickCheck
    quickcheck-instances
    ram
    random
    schema-profunctor
    servant
    servant-multipart
    servant-server
    shelly
    silently
    string-conversions
    temporary
    text
    time
    time-hourglass
    tinylog
    transformers
    types-common
    uniplate
    uri-bytestring
    utf8-string
    uuid
    wai
    wai-extra
    warp
    word8
    xml-conduit
    xml-conduit-writer
    xml-hamlet
    xml-types
    yaml
  ];
  testToolDepends = [ hspec-discover ];
  description = "Library and example web app for the SAML Web-based SSO profile";
  license = lib.meta.getLicenseFromSpdxId "AGPL-3.0-only";
}
