# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, base
, base64-bytestring
, binary
, bytestring
, case-insensitive
, containers
, cookie
, crypton
, crypton-asn1-types
, crypton-x509
, data-default
, directory
, dns
, email-validate
, errors
, extra
, file-path-th
, filepath
, foundation
, ghc-prim
, hedgehog
, hedgehog-quickcheck
, hsaml2
, hspec
, hspec-core
, hspec-wai
, http-media
, http-types
, hxt
, imports
, invertible-hxt
, lens
, lib
, mtl
, network-uri
, openapi3
, pretty-show
, process
, QuickCheck
, quickcheck-instances
, ram
, random
, schema-profunctor
, servant
, servant-multipart
, servant-server
, silently
, string-conversions
, temporary
, text
, time
, time-hourglass
, tinylog
, types-common
, uniplate
, uri-bytestring
, utf8-string
, uuid
, wai
, wai-extra
, wai-utilities
, word8
, xml-conduit
, xml-hamlet
, yaml
}:
mkDerivation {
  pname = "saml2-web-sso";
  version = "0.20";
  src = ./.;
  libraryHaskellDepends = [
    aeson
    base
    base64-bytestring
    binary
    bytestring
    case-insensitive
    containers
    cookie
    crypton
    crypton-asn1-types
    crypton-x509
    directory
    dns
    email-validate
    errors
    extra
    file-path-th
    filepath
    foundation
    ghc-prim
    hedgehog
    hedgehog-quickcheck
    hsaml2
    hspec
    hspec-wai
    http-media
    http-types
    hxt
    invertible-hxt
    lens
    mtl
    network-uri
    openapi3
    pretty-show
    process
    QuickCheck
    quickcheck-instances
    ram
    random
    schema-profunctor
    servant
    servant-multipart
    servant-server
    silently
    string-conversions
    temporary
    text
    time
    time-hourglass
    tinylog
    types-common
    uniplate
    uri-bytestring
    utf8-string
    uuid
    wai
    wai-extra
    wai-utilities
    word8
    xml-conduit
    xml-hamlet
    yaml
  ];
  testHaskellDepends = [
    aeson
    base
    base64-bytestring
    bytestring
    case-insensitive
    containers
    crypton
    crypton-x509
    data-default
    errors
    hedgehog
    hsaml2
    hspec
    hspec-core
    hspec-wai
    hxt
    imports
    lens
    mtl
    pretty-show
    QuickCheck
    schema-profunctor
    servant-server
    string-conversions
    text
    time-hourglass
    tinylog
    types-common
    uri-bytestring
    uuid
    wai-extra
    xml-conduit
    xml-hamlet
    yaml
  ];
  description = "Library and example web app for the SAML Web-based SSO profile";
  license = lib.meta.getLicenseFromSpdxId "AGPL-3.0-only";
}
