#!/usr/bin/env bash
set -e

exec 2>&1

# defaults
USER=${USER:-www-data}
APP=cannon
CONFIG=${CONFIG:-/etc/${APP}/${APP}.yaml}
HOME=${APP_HOME:-/opt/$APP}
BIN=$HOME/bin/$APP

if [ ! -f $CONFIG ]; then exec chpst -u $USER get_config; fi

export GHCRTS='-I5'

cd $HOME

ulimit -n 131072

exec chpst -u $USER $BIN --config-file=${CONFIG}


#    -p ${CANNON_PORT?'unset'} \
#    --host ${CANNON_HOST?'unset'} \
#    --external-host ${CANNON_EXTERNAL_HOST:-127.0.0.1} \
#    --gundeck-host=${CANNON_GUNDECK_HOST?'unset'} \
#    --gundeck-port=${CANNON_GUNDECK_PORT?'unset'}
