#!/usr/bin/env bash
set -e

exec 2>&1

APP=spar

# defaults
USER=${USER:-www-data}
CONFIG=${CONFIG:-/etc/${APP}/${APP}.yaml}
HOME=${APP_HOME:-/opt/$APP}
BIN=$HOME/bin/$APP

export LOG_LEVEL=${SPAR_LOG_LEVEL:-Info}
export LOG_NETSTR=${SPAR_LOG_NETSTR:-True}

if [ ! -f $CONFIG ]; then exec chpst -u $USER get_config; fi

cd $HOME

ulimit -n 65536

exec chpst -u $USER $BIN --config-file=${CONFIG}
