# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, amazonka
, amazonka-core
, amazonka-dynamodb
, amazonka-ses
, amazonka-sqs
, amqp
, async
, attoparsec
, auto-update
, base
, base-prelude
, base16-bytestring
, base64-bytestring
, bilge
, binary
, bloodhound
, brig-types
, bytestring
, bytestring-conversion
, case-insensitive
, cassandra-util
, comonad
, conduit
, containers
, cookie
, cql
, cryptobox-haskell
, crypton
, currency-codes
, data-default
, data-timeout
, dns
, dns-util
, either
, email-validate
, enclosed-exceptions
, errors
, exceptions
, extended
, extra
, federator
, file-embed
, file-embed-lzma
, filepath
, fsnotify
, galley-types
, gitignoreSource
, gundeck-types
, hashable
, hscim
, HsOpenSSL
, http-api-data
, http-client
, http-client-openssl
, http-client-tls
, http-media
, http-reverse-proxy
, http-types
, http2-manager
, imports
, insert-ordered-containers
, iproute
, iso639
, jose
, jwt-tools
, lens
, lens-aeson
, lib
, memory
, metrics-core
, metrics-wai
, mime
, mime-mail
, mmorph
, MonadRandom
, mtl
, network
, network-conduit-tls
, network-uri
, openapi3
, optparse-applicative
, pem
, pipes
, polysemy
, polysemy-conc
, polysemy-plugin
, polysemy-time
, polysemy-wire-zoo
, postie
, process
, prometheus-client
, proto-lens
, QuickCheck
, random
, random-shuffle
, raw-strings-qq
, resourcet
, retry
, safe
, safe-exceptions
, saml2-web-sso
, schema-profunctor
, scientific
, servant
, servant-client
, servant-client-core
, servant-openapi3
, servant-server
, servant-swagger-ui
, sodium-crypto-sign
, spar
, split
, ssl-util
, statistics
, stomp-queue
, streaming-commons
, string-conversions
, tasty
, tasty-ant-xml
, tasty-cannon
, tasty-hunit
, tasty-quickcheck
, template
, template-haskell
, temporary
, text
, text-icu-translit
, time
, time-out
, time-units
, tinylog
, transformers
, transitive-anns
, types-common
, types-common-aws
, types-common-journal
, unliftio
, unordered-containers
, uri-bytestring
, utf8-string
, uuid
, vector
, wai
, wai-extra
, wai-middleware-gunzip
, wai-route
, wai-utilities
, warp
, warp-tls
, wire-api
, wire-api-federation
, wire-subsystems
, yaml
, zauth
}:
mkDerivation {
  pname = "brig";
  version = "2.0";
  src = gitignoreSource ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson
    amazonka
    amazonka-core
    amazonka-dynamodb
    amazonka-ses
    amazonka-sqs
    amqp
    async
    auto-update
    base
    base-prelude
    base16-bytestring
    base64-bytestring
    bilge
    bloodhound
    brig-types
    bytestring
    bytestring-conversion
    cassandra-util
    comonad
    conduit
    containers
    cookie
    cql
    cryptobox-haskell
    crypton
    currency-codes
    data-default
    dns
    dns-util
    enclosed-exceptions
    errors
    exceptions
    extended
    extra
    file-embed
    file-embed-lzma
    filepath
    fsnotify
    galley-types
    gundeck-types
    hashable
    HsOpenSSL
    http-client
    http-client-openssl
    http-media
    http-types
    http2-manager
    imports
    insert-ordered-containers
    iproute
    iso639
    jose
    jwt-tools
    lens
    lens-aeson
    memory
    metrics-core
    metrics-wai
    mime
    mime-mail
    mmorph
    MonadRandom
    mtl
    network
    network-conduit-tls
    openapi3
    optparse-applicative
    polysemy
    polysemy-conc
    polysemy-plugin
    polysemy-time
    polysemy-wire-zoo
    prometheus-client
    proto-lens
    random-shuffle
    raw-strings-qq
    resourcet
    retry
    safe-exceptions
    saml2-web-sso
    schema-profunctor
    scientific
    servant
    servant-openapi3
    servant-server
    servant-swagger-ui
    sodium-crypto-sign
    split
    ssl-util
    statistics
    stomp-queue
    template
    template-haskell
    text
    text-icu-translit
    time
    time-out
    time-units
    tinylog
    transformers
    transitive-anns
    types-common
    types-common-aws
    types-common-journal
    unliftio
    unordered-containers
    uri-bytestring
    utf8-string
    uuid
    vector
    wai
    wai-extra
    wai-middleware-gunzip
    wai-utilities
    wire-api
    wire-api-federation
    wire-subsystems
    zauth
  ];
  executableHaskellDepends = [
    aeson
    async
    attoparsec
    base
    base16-bytestring
    bilge
    bloodhound
    brig-types
    bytestring
    bytestring-conversion
    case-insensitive
    cassandra-util
    containers
    cookie
    data-default
    data-timeout
    either
    email-validate
    exceptions
    extended
    extra
    federator
    filepath
    galley-types
    hscim
    HsOpenSSL
    http-api-data
    http-client
    http-client-tls
    http-media
    http-reverse-proxy
    http-types
    imports
    jose
    lens
    lens-aeson
    metrics-wai
    mime
    mime-mail
    MonadRandom
    mtl
    network
    network-uri
    optparse-applicative
    pem
    pipes
    polysemy
    polysemy-wire-zoo
    postie
    process
    proto-lens
    QuickCheck
    random
    random-shuffle
    raw-strings-qq
    retry
    safe
    saml2-web-sso
    servant
    servant-client
    servant-client-core
    spar
    streaming-commons
    string-conversions
    tasty
    tasty-ant-xml
    tasty-cannon
    tasty-hunit
    temporary
    text
    time
    time-units
    tinylog
    transformers
    types-common
    types-common-aws
    types-common-journal
    unliftio
    unordered-containers
    uri-bytestring
    uuid
    vector
    wai
    wai-extra
    wai-route
    wai-utilities
    warp
    warp-tls
    wire-api
    wire-api-federation
    wire-subsystems
    yaml
    zauth
  ];
  testHaskellDepends = [
    aeson
    base
    binary
    brig-types
    bytestring
    containers
    data-timeout
    dns
    dns-util
    exceptions
    HsOpenSSL
    imports
    lens
    polysemy
    polysemy-wire-zoo
    tasty
    tasty-hunit
    tasty-quickcheck
    text
    time
    tinylog
    types-common
    unliftio
    uri-bytestring
    uuid
    wire-api
    wire-subsystems
  ];
  description = "User Service";
  license = lib.licenses.agpl3Only;
}
