# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation, amazonka, amazonka-core, amazonka-sqs, base
, base64-bytestring, gitignoreSource, imports, lens, lib
, proto-lens, resourcet, safe, text, time, unliftio
}:
mkDerivation {
  pname = "types-common-aws";
  version = "0.16.0";
  src = gitignoreSource ./.;
  libraryHaskellDepends = [
    amazonka amazonka-core amazonka-sqs base base64-bytestring imports
    lens proto-lens resourcet safe text time unliftio
  ];
  description = "Shared AWS type definitions";
  license = lib.licenses.agpl3Only;
}
