# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, base
, bytestring
, containers
, gitignoreSource
, hs-opentelemetry-api
, hs-opentelemetry-instrumentation-http-client
, hs-opentelemetry-sdk
, hs-opentelemetry-utils-exceptions
, http-client
, http-types
, kan-extensions
, lib
, mtl
, servant-client
, servant-client-core
, text
, unliftio
}:
mkDerivation {
  pname = "wire-otel";
  version = "0.1.0.0";
  src = gitignoreSource ./.;
  libraryHaskellDepends = [
    base
    bytestring
    containers
    hs-opentelemetry-api
    hs-opentelemetry-instrumentation-http-client
    hs-opentelemetry-sdk
    hs-opentelemetry-utils-exceptions
    http-client
    http-types
    kan-extensions
    mtl
    servant-client
    servant-client-core
    text
    unliftio
  ];
  homepage = "https://wire.com/";
  license = lib.licenses.agpl3Only;
}
