# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, aeson-pretty
, base
, bilge
, bytestring
, bytestring-conversion
, cassandra-util
, conduit
, containers
, cql
, exceptions
, galley
, gitignoreSource
, HsOpenSSL
, http-client
, http-client-openssl
, http-types
, imports
, lens
, lib
, monoidal-containers
, optparse-applicative
, retry
, ssl-util
, tinylog
, types-common
, uri-bytestring
, wire-api
}:
mkDerivation {
  pname = "bots";
  version = "1.0.0";
  src = gitignoreSource ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson
    aeson-pretty
    bilge
    bytestring
    bytestring-conversion
    cassandra-util
    conduit
    containers
    cql
    exceptions
    galley
    HsOpenSSL
    http-client
    http-client-openssl
    http-types
    imports
    lens
    monoidal-containers
    optparse-applicative
    retry
    ssl-util
    tinylog
    types-common
    uri-bytestring
    wire-api
  ];
  executableHaskellDepends = [ base ];
  description = "find bots";
  license = lib.licenses.agpl3Only;
  mainProgram = "bots";
}
