image:
  repository: motoserver/moto
  tag: 5.1.22

awsCliImage:
  repository: amazon/aws-cli
  tag: 2.34.7

service:
  internalPort: 4575
  externalPort: 4575

resources:
  limits:
    cpu: "200m"
    memory: 500Mi
  requests:
    cpu: "100m"
    memory: 100Mi

applications:
  - name: integration-test
    platform: GCM
    credential: testkey
  - name: integration-test
    platform: APNS_SANDBOX
    credential: testprivatekey
  - name: integration-com.wire.ent
    platform: APNS_SANDBOX
    credential: testprivatekey
