# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, aeson-pretty
, base
, bytestring
, cassandra-util
, conduit
, containers
, cql
, exceptions
, gitignoreSource
, imports
, lens
, lib
, optparse-applicative
, time
, tinylog
, types-common
, wire-api
}:
mkDerivation {
  pname = "conference-feature";
  version = "1.0.0";
  src = gitignoreSource ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson
    aeson-pretty
    base
    bytestring
    cassandra-util
    conduit
    containers
    cql
    exceptions
    imports
    lens
    optparse-applicative
    time
    tinylog
    types-common
    wire-api
  ];
  executableHaskellDepends = [ base ];
  description = "check the user's conference feature";
  license = lib.licenses.agpl3Only;
  mainProgram = "conference-feature";
}
