apiVersion: v1
description: Galley (part of Wire Server) - Conversations
name: galley
version: 0.0.42
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - name: galley
      image: quay.io/wire/galley:do-not-use
    - name: galley-integration
      image: quay.io/wire/galley-integration:do-not-use
