apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-index-create
  labels:
    app: elasticsearch-index-create
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app: elasticsearch-index-create
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: brig-config
          configMap:
            name: brig
        - name: brig-secrets
          secret:
            secretName: brig
        {{- if .Values.elasticsearchTlsEnabled }}
        - name: elasticsearch-ca
          secret:
            secretName: {{ .Values.secrets.elasticsearchCaSecretName }}
        {{- end }}
      initContainers:
        # Creates index in elasticsearch only when it doesn't exist.
        # Does nothing if the index exists.
        - name: brig-index-create
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: brig-config
              mountPath: /etc/wire/brig/conf
            - name: brig-secrets
              mountPath: /etc/wire/brig/secrets
            {{- if .Values.elasticsearchTlsEnabled }}
            - name: elasticsearch-ca
              mountPath: "/etc/wire/brig/elasticsearch-ca"
            {{- end }}
          {{- if eq (include "includeSecurityContext" .) "true" }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- end }}
          args:
            - yaml
            - --config-file
            - /etc/wire/brig/conf/brig.yaml
            - create
            - --elasticsearch-shards={{ default 5 .Values.elasticsearch.shards }}
            - --elasticsearch-replicas={{ default 2 .Values.elasticsearch.replicas }}
            - --elasticsearch-refresh-interval={{ default 5 .Values.elasticsearch.refreshInterval }}
            {{- if .Values.elasticsearch.delete_template }}
            - --delete-template
            - "{{ .Values.elasticsearch.delete_template }}"
            {{- end }}
      containers:
        - name: brig-index-update-mapping
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          volumeMounts:
            - name: brig-config
              mountPath: /etc/wire/brig/conf
            - name: brig-secrets
              mountPath: /etc/wire/brig/secrets
            {{- if .Values.elasticsearchTlsEnabled }}
            - name: elasticsearch-ca
              mountPath: "/etc/wire/brig/elasticsearch-ca"
            {{- end }}
          {{- if eq (include "includeSecurityContext" .) "true" }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- end }}
          args:
            - yaml
            - --config-file
            - /etc/wire/brig/conf/brig.yaml
            - update-mapping
