apiVersion: batch/v1
kind: Job
metadata:
  name: brig-index-migrate-data
  labels:
    app: elasticsearch-index-migrate-data
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app: elasticsearch-index-migrate-data
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: OnFailure
      containers:
        # Reindexes all users when a new migration is detected.
        - name: brig-index
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          args:
            - yaml
            - --config-file
            - /etc/wire/brig/conf/brig.yaml
            - migrate-data
          volumeMounts:
            - name: brig-config
              mountPath: /etc/wire/brig/conf
          {{- if hasKey .Values.secrets "elasticsearch" }}
            - name: "elasticsearch-index-secrets"
              mountPath: "/etc/wire/brig/secrets"
          {{- end }}
          {{- if eq (include "useCassandraTLS" .Values) "true" }}
            - name: elasticsearch-index-migrate-cassandra-client-ca
              mountPath: "/etc/wire/brig/cassandra"
          {{- end }}
          {{- if eq (include "configureElasticsearchCa" .Values) "true" }}
            - name: elasticsearch-ca
              mountPath: "/etc/wire/brig/elasticsearch-ca"
          {{- end }}
      volumes:
        - name: brig-config
          configMap:
            name: brig
        {{- if hasKey .Values.secrets "elasticsearch" }}
        - name: elasticsearch-index-secrets
          secret:
            secretName: elasticsearch-index
        {{- end }}
        {{- if eq (include "useCassandraTLS" .Values) "true" }}
        - name: elasticsearch-index-migrate-cassandra-client-ca
          secret:
            secretName: {{ include "cassandraTlsSecretName" .Values }}
        {{- end }}
        {{- if eq (include "configureElasticsearchCa" .Values) "true" }}
        - name: elasticsearch-ca
          secret:
            secretName: {{ include "elasticsearchTlsSecretName" .Values }}
        {{- end }}
