apiVersion: batch/v1
kind: Job
metadata:
  name: brig-index-migrate-data
  labels:
    app: elasticsearch-index-migrate-data
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app: elasticsearch-index-migrate-data
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: OnFailure
      containers:
        # Reindexes all users when a new migration is detected.
        - name: brig-index
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          args:
            - yaml
            - --config-file
            - /etc/wire/brig/conf/brig.yaml
            - migrate-data
          volumeMounts:
            - name: brig-config
              mountPath: /etc/wire/brig/conf
            - name: brig-secrets
              mountPath: /etc/wire/brig/secrets
          {{- if .Values.cassandraTlsEnabled }}
            - name: cassandra-ca
              mountPath: "/etc/wire/brig/cassandra"
          {{- end }}
          {{- if .Values.elasticsearchTlsEnabled }}
            - name: elasticsearch-ca
              mountPath: "/etc/wire/brig/elasticsearch-ca"
          {{- end }}
      volumes:
        - name: brig-config
          configMap:
            name: brig
        - name: brig-secrets
          secret:
            secretName: brig
        {{- if .Values.cassandraTlsEnabled }}
        - name: cassandra-ca
          secret:
            secretName: {{ .Values.secrets.cassandraCaSecretName }}
        {{- end }}
        {{- if .Values.elasticsearchTlsEnabled }}
        - name: elasticsearch-ca
          secret:
            secretName: {{ .Values.secrets.elasticsearchCaSecretName }}
        {{- end }}
