# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, base
, bytestring-conversion
, cassandra-util
, conduit
, containers
, cql
, gitignoreSource
, imports
, lens
, lib
, optparse-applicative
, string-conversions
, tinylog
, transformers
, types-common
, wire-api
}:
mkDerivation {
  pname = "bot-info";
  version = "1.0.0";
  src = gitignoreSource ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    bytestring-conversion
    cassandra-util
    conduit
    containers
    cql
    imports
    lens
    optparse-applicative
    string-conversions
    tinylog
    transformers
    types-common
    wire-api
  ];
  executableHaskellDepends = [ base ];
  description = "get bot info from cassandra";
  license = lib.licenses.agpl3Only;
  mainProgram = "bot-info";
}
