# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, aeson-pretty
, base
, bytestring
, containers
, filepath
, hspec
, imports
, lib
, optparse-applicative
, text
, vector
}:
mkDerivation {
  pname = "lint-openapi-regression";
  version = "0.1.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson
    aeson-pretty
    bytestring
    containers
    imports
    text
    vector
  ];
  executableHaskellDepends = [
    base
    containers
    filepath
    imports
    optparse-applicative
    text
  ];
  testHaskellDepends = [ aeson containers hspec imports text ];
  description = "OpenAPI backward-compatibility linter";
  license = lib.licenses.agpl3Only;
  mainProgram = "lint-openapi-regression";
}
