# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, aeson-qq
, amazonka
, amazonka-sqs
, async
, base
, base64-bytestring
, bilge
, binary
, brig-types
, bytestring
, bytestring-conversion
, call-stack
, case-insensitive
, cassandra-util
, cassava
, cereal
, comonad
, containers
, cookie
, cryptonite
, currency-codes
, data-default
, data-timeout
, directory
, errors
, exceptions
, extended
, extra
, federator
, filepath
, galley
, galley-types
, gitignoreSource
, gundeck-types
, hex
, HsOpenSSL
, HsOpenSSL-x509-system
, hspec
, http-client
, http-client-openssl
, http-client-tls
, http-media
, http-types
, imports
, kan-extensions
, lens
, lens-aeson
, lib
, memory
, metrics-wai
, mtl
, network
, network-uri
, optparse-applicative
, pem
, process
, proto-lens
, protobuf
, QuickCheck
, quickcheck-instances
, random
, raw-strings-qq
, retry
, safe
, saml2-web-sso
, schema-profunctor
, servant
, servant-client
, servant-client-core
, servant-server
, servant-swagger
, servant-swagger-ui
, singletons
, singletons-th
, sop-core
, split
, ssl-util
, streaming-commons
, string-conversions
, swagger2
, tagged
, tasty
, tasty-cannon
, tasty-hunit
, temporary
, text
, time
, tinylog
, tls
, transformers
, types-common
, types-common-aws
, types-common-journal
, unix
, unliftio
, unordered-containers
, uri-bytestring
, uuid
, uuid-types
, vector
, wai
, wai-extra
, wai-predicates
, wai-routing
, wai-utilities
, warp
, warp-tls
, wire-api
, wire-api-federation
, wire-message-proto-lens
, yaml
}:
mkDerivation {
  pname = "stern";
  version = "1.7.2";
  src = gitignoreSource ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson
    base
    bilge
    brig-types
    bytestring
    bytestring-conversion
    containers
    data-default
    errors
    exceptions
    extended
    galley-types
    gundeck-types
    http-client
    http-types
    imports
    lens
    metrics-wai
    mtl
    retry
    schema-profunctor
    servant
    servant-server
    servant-swagger
    servant-swagger-ui
    split
    string-conversions
    swagger2
    text
    tinylog
    transformers
    types-common
    unliftio
    unordered-containers
    uuid
    wai
    wai-extra
    wai-predicates
    wai-routing
    wai-utilities
    warp
    wire-api
    yaml
  ];
  executableHaskellDepends = [
    aeson
    aeson-qq
    amazonka
    amazonka-sqs
    async
    base
    base64-bytestring
    bilge
    binary
    brig-types
    bytestring
    bytestring-conversion
    call-stack
    case-insensitive
    cassandra-util
    cassava
    cereal
    comonad
    containers
    cookie
    cryptonite
    currency-codes
    data-default
    data-timeout
    directory
    errors
    exceptions
    extended
    extra
    federator
    filepath
    galley
    galley-types
    gundeck-types
    hex
    HsOpenSSL
    HsOpenSSL-x509-system
    hspec
    http-client
    http-client-openssl
    http-client-tls
    http-media
    http-types
    imports
    kan-extensions
    lens
    lens-aeson
    memory
    metrics-wai
    mtl
    network
    network-uri
    optparse-applicative
    pem
    process
    proto-lens
    protobuf
    QuickCheck
    quickcheck-instances
    random
    raw-strings-qq
    retry
    safe
    saml2-web-sso
    schema-profunctor
    servant
    servant-client
    servant-client-core
    servant-server
    servant-swagger
    singletons
    singletons-th
    sop-core
    ssl-util
    streaming-commons
    string-conversions
    tagged
    tasty
    tasty-cannon
    tasty-hunit
    temporary
    text
    time
    tinylog
    tls
    transformers
    types-common
    types-common-aws
    types-common-journal
    unix
    unliftio
    unordered-containers
    uri-bytestring
    uuid
    uuid-types
    vector
    wai
    wai-extra
    wai-utilities
    warp
    warp-tls
    wire-api
    wire-api-federation
    wire-message-proto-lens
    yaml
  ];
  testHaskellDepends = [ base tasty tasty-hunit wire-api ];
  license = lib.licenses.agpl3Only;
}
