# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, base
, bilge
, brig-types
, bytestring
, bytestring-conversion
, containers
, data-default
, errors
, exceptions
, extended
, galley-types
, gitignoreSource
, gundeck-types
, http-client
, http-types
, imports
, lens
, lib
, metrics-wai
, mtl
, retry
, schema-profunctor
, servant
, servant-server
, servant-swagger
, servant-swagger-ui
, split
, string-conversions
, swagger2
, tasty
, tasty-hunit
, text
, tinylog
, transformers
, types-common
, unliftio
, unordered-containers
, uuid
, wai
, wai-extra
, wai-predicates
, wai-routing
, wai-utilities
, warp
, wire-api
, yaml
}:
mkDerivation {
  pname = "stern";
  version = "1.7.2";
  src = gitignoreSource ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson
    base
    bilge
    brig-types
    bytestring
    bytestring-conversion
    containers
    data-default
    errors
    exceptions
    extended
    galley-types
    gundeck-types
    http-client
    http-types
    imports
    lens
    metrics-wai
    mtl
    retry
    schema-profunctor
    servant
    servant-server
    servant-swagger
    servant-swagger-ui
    split
    string-conversions
    swagger2
    text
    tinylog
    transformers
    types-common
    unliftio
    unordered-containers
    uuid
    wai
    wai-extra
    wai-predicates
    wai-routing
    wai-utilities
    warp
    wire-api
    yaml
  ];
  executableHaskellDepends = [
    base
    extended
    imports
    types-common
    unliftio
  ];
  testHaskellDepends = [ base tasty tasty-hunit wire-api ];
  license = lib.licenses.agpl3Only;
  mainProgram = "stern";
}
