{
 "title": "Message Stats",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "kube_namespace_labels" } }
  ]
 },
 "panels": [
  { "title": "Brig Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Registrations/invitations/code requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{handler=\"/teams/:tid/invitations\", status_code=\"201\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "invitations/sec(201)"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{handler=\"/register\", status_code=\"201\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "registration/sec(201)"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{handler=\"/activate/send\", status_code=~\"200\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "code_requests/sec(200)"
    }
   ]
  },
  {
   "title": "Prekey fetch count",
   "type": "timeseries",
   "description": "A client can fetch many prekeys with one API call, so the count here just represents how many calls are made to the API",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{namespace=\"$namespace\", handler=~\"/federation/claim-multi-prekey-bundle|/users/:uid/prekeys/:client|/users/:uid_domain/:uid/prekeys/:client|/users/:uid/prekeys|/users/:uid_domain/:uid/prekeys/users/prekys|/users/list-prekeys\"}[5m]))",
     "legendFormat": "API Calls"
    }
   ]
  },
  { "title": "Galley Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Message sending latencies for local and remote conversations",
   "type": "heatmap",
   "description": "Includes messages that originate from local clients or remote users in local conversations",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{handler=~\"(/conversations/:cnv/otr/messages|/conversations/:cnv_domain/:cnv/proteus/messages|/federation/send-message)\", namespace=\"$namespace\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Latencies for messages received from remote conversations",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{handler=\"/federation/on-message-sent\", namespace=\"$namespace\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Messages Sent every 5m",
   "type": "graph",
   "description": "Messages sent from local clients to remote conversations are duplicated, if there are any other local clients involved",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{handler=~\"(/conversations/:cnv/otr/messages|/conversations/:cnv_domain/:cnv/proteus/messages|/federation/send-message|/federation/on-message-sent)\", status_code=~\"2..\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Messages sent"
    }
   ]
  },
  {
   "title": "Proteus Message Receives as % by Status Code",
   "type": "graph",
   "description": "Does not include federation endpoints as they do not express errors in HTTP status",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{role=\"galley\", handler=~\"(/conversations/:cnv/otr/messages|/conversations/:cnv_domain/:cnv/proteus/messages)\", status_code=~\"2..\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{role=\"galley\", handler=~\"(/conversations/:cnv/otr/messages|/conversations/:cnv_domain/:cnv/proteus/messages)\", status_code=~\"4..\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{role=\"galley\", handler=~\"(/conversations/:cnv/otr/messages|/conversations/:cnv_domain/:cnv/proteus/messages)\", status_code=~\"5..\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  { "title": "Cannon Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Connected Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(net_websocket_clients{namespace=\"$namespace\"})",
     "legendFormat": "Connected Clients"
    }
   ]
  },
  { "title": "Cargohold stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Assets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{handler=\"/assets/v3\", status_code=\"201\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "uploaded/sec"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{handler=\"/assets/v3/:key\", status_code=\"302\", namespace=\"$namespace\"}[5m]))\n",
     "legendFormat": "downloaded/sec"
    }
   ]
  },
  { "title": "Gundeck Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Message Push Latencies",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{handler=\"/i/push/v2\", namespace=\"$namespace\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Native Push (Outgoing)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(push_native_success[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "-sum(increase(push_native_disabled[5m]))",
     "legendFormat": "-Disabled"
    },
    {
     "expr": "-sum(increase(push_native_invalid{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "-Invalid"
    },
    {
     "expr": "-sum(increase(push_native_errors{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "-Errors"
    }
   ]
  },
  {
   "title": "Push Rate (incoming)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{role=\"gundeck\", handler=\"/i/push/v2\", namespace=\"$namespace\"}[5m])) by (status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Push Status Codes as %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{handler=\"/i/push/v2\", namespace=\"$namespace\"}) by (status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  }
 ]
}