{
 "title": "Wire Services",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "brig,galley,cannon,gundeck,cargohold,spar,proxy,federator"
   },
   { "name": "namespace", "query": { "query": "kube_namespace_labels" } }
  ]
 },
 "panels": [
  {
   "title": "README",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Haskell Service Statistics\n## Change the $(service) and $(namespace) variables to filter stats"
   }
  },
  { "title": "Global Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "5XXs By Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"5..\", namespace=\"$namespace\"}[5m])) by (role)",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "5XX/s per handler (current time range) - all services",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"5..\", namespace=\"$namespace\"}[$__range])) by (role, handler)",
     "legendFormat": "# 5XXs"
    }
   ]
  },
  { "title": "$service request stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Request Error Breakdown - $service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"4..\", role=\"$service\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"5..\", role=\"$service\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "4XX/s per handler (current time range) - $service",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"4..\", role=\"$service\", namespace=\"$namespace\"}[$__range])) by (handler)",
     "legendFormat": "# 5XXs"
    }
   ]
  },
  {
   "title": "5XX/s per handler (current time range) - $service",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"5..\", role=\"$service\", namespace=\"$namespace\"}[$__range])) by (handler)",
     "legendFormat": "# 5XXs"
    }
   ]
  },
  {
   "title": "Network Traffic - $service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Num / KB" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"$service.*\", namespace=\"$namespace\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}",
     "target": "alias(scale(scaleToSeconds(nonNegativeDerivative(sumSeries(gundeck.*.eu-west-1.compute.internal.interface.eth0.if_octets.rx)), 1), 0.001), 'kb/s - inbound')"
    }
   ]
  },
  { "title": "$service stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU % (Mean) - $service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_cpu_load_average_10s{pod=~\"$service.*\", namespace=\"$namespace\"}) by (pod_name) * 100",
     "legendFormat": "{{ pod_name }}",
     "target": "alias(averageSeries(gundeck.*.eu-west-1.compute.internal.load.load.shortterm), 'load - shorterm')"
    }
   ]
  },
  {
   "title": "Memory Usage - $service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$service.*\", namespace=\"$namespace\"}) by (pod_name) / (1024 * 1024)",
     "legendFormat": "{{ pod_name }}",
     "target": "alias(scale(averageSeries(gundeck.*.eu-west-1.compute.internal.memory.memory.used), 0.000001), 'used')"
    }
   ]
  },
  {
   "title": "Inbound Connections - $service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(net_connections{role=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "Inbound Connections"
    }
   ]
  }
 ]
}