apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "outlook.fullname" . }}"
  labels:
    {{- include "outlook.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ required "Must specify allowOrigin" .Values.allowOrigin }}"
spec:
  ingressClassName: "{{ .Values.config.ingressClass }}"
  tls:
    - hosts:
        - "{{ .Values.host }}"
      secretName: "{{ include "outlook.fullname" . }}"
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "outlook.fullname" . }}
                port:
                  number: 8080
