apiVersion: v1
description: A Helm chart for ingresses and services on Kubernetes
name: nginx-ingress-services
version: 0.0.42
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: "[]"
