apiVersion: v1
description: Dummy ephemeral SQS service
name: fake-aws-sqs
version: 0.0.42
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - name: elasticmq-native
      image: docker.io/softwaremill/elasticmq-native:1.6.11
