# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, bytestring
, containers
, extra
, filepath
, ghc
, ghc-paths
, gitignoreSource
, hspec
, imports
, lib
}:
mkDerivation {
  pname = "find-tests";
  version = "1.0.0";
  src = gitignoreSource ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [ aeson containers extra ghc imports ];
  executableHaskellDepends = [
    aeson
    bytestring
    containers
    extra
    filepath
    ghc
    ghc-paths
    imports
  ];
  testHaskellDepends = [ aeson bytestring containers hspec imports ];
  description = "Identify tests listed in an audit requirements document maintained by Wire QA";
  license = lib.licenses.agpl3Only;
  mainProgram = "find-tests";
}
