apiVersion: v1
description: Wrapper chart for https://github.com/groundhog2k/helm-charts/tree/redis-1.3.8/charts/redis
name: redis-ephemeral
version: 0.0.42
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - name: redis
      image: docker.io/redis:7.4.6
      dependency: redis
    - name: redis-exporter
      image: docker.io/oliver006/redis_exporter:v1.77.0
      dependency: redis
