apiVersion: v1
description: Wrapper chart for stable/redis
name: redis-ephemeral
version: 0.0.42
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - dependency: redis
      name: redis
      image: docker.io/bitnamilegacy/redis:6.2.7-debian-11-r0
