# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mls.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmls.proto\x12\x03mls\"\x83\x01\n\x0fGroupInfoBundle\x12+\n\x0fgroup_info_type\x18\x01 \x02(\x0e\x32\x12.mls.GroupInfoType\x12/\n\x11ratchet_tree_type\x18\x02 \x02(\x0e\x32\x14.mls.RatchetTreeType\x12\x12\n\ngroup_info\x18\x03 \x02(\x0c\"`\n\x0c\x43ommitBundle\x12\x0e\n\x06\x63ommit\x18\x01 \x02(\x0c\x12\x0f\n\x07welcome\x18\x02 \x01(\x0c\x12/\n\x11group_info_bundle\x18\x03 \x02(\x0b\x32\x14.mls.GroupInfoBundle*K\n\rGroupInfoType\x12\x16\n\x12PUBLIC_GROUP_STATE\x10\x01\x12\x0e\n\nGROUP_INFO\x10\x02\x12\x12\n\x0eGROUP_INFO_JWE\x10\x03*5\n\x0fRatchetTreeType\x12\x08\n\x04\x46ULL\x10\x01\x12\t\n\x05\x44\x45LTA\x10\x02\x12\r\n\tREFERENCE\x10\x03\x42\x1a\n\x11\x63om.wire.messagesB\x03MlsH\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mls_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021com.wire.messagesB\003MlsH\003'
  _GROUPINFOTYPE._serialized_start=250
  _GROUPINFOTYPE._serialized_end=325
  _RATCHETTREETYPE._serialized_start=327
  _RATCHETTREETYPE._serialized_end=380
  _GROUPINFOBUNDLE._serialized_start=19
  _GROUPINFOBUNDLE._serialized_end=150
  _COMMITBUNDLE._serialized_start=152
  _COMMITBUNDLE._serialized_end=248
# @@protoc_insertion_point(module_scope)
