# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation, base, base64-bytestring, bytestring
, bytestring-conversion, either, extra, gitignoreSource, hspec
, http-types, imports, lib, QuickCheck, rusty_jwt_tools_ffi
, string-conversions, text, transformers, unliftio, uuid
}:
mkDerivation {
  pname = "jwt-tools";
  version = "0.1.0";
  src = gitignoreSource ./.;
  libraryHaskellDepends = [
    base base64-bytestring bytestring bytestring-conversion http-types
    imports QuickCheck string-conversions transformers unliftio
  ];
  librarySystemDepends = [ rusty_jwt_tools_ffi ];
  testHaskellDepends = [
    base base64-bytestring bytestring bytestring-conversion either
    extra hspec http-types imports QuickCheck string-conversions text
    transformers uuid
  ];
  description = "FFI to rusty-jwt-tools";
  license = lib.licenses.agpl3Only;
}
