# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, async
, base
, bytestring
, containers
, extended
, hasql
, hasql-resource-pool
, hasql-transaction
, hspec
, hspec-discover
, http-types
, imports
, lib
, optparse-applicative
, polysemy
, postgresql-connection-string
, primitive
, prometheus-client
, QuickCheck
, random
, text
, types-common
, unliftio
, uuid-types
, vector
, wai
, warp
, wire-api
, wire-subsystems
}:
mkDerivation {
  pname = "fan-in-perf";
  version = "1.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson
    async
    base
    bytestring
    containers
    extended
    hasql-resource-pool
    hasql-transaction
    http-types
    imports
    optparse-applicative
    polysemy
    postgresql-connection-string
    primitive
    prometheus-client
    random
    text
    types-common
    unliftio
    uuid-types
    vector
    wai
    warp
    wire-api
    wire-subsystems
  ];
  executableHaskellDepends = [ base imports optparse-applicative ];
  testHaskellDepends = [
    aeson
    async
    base
    bytestring
    containers
    hasql
    hasql-resource-pool
    hspec
    http-types
    imports
    optparse-applicative
    prometheus-client
    QuickCheck
    random
    text
    types-common
    vector
    wai
    wire-api
    wire-subsystems
  ];
  testToolDepends = [ hspec-discover ];
  description = "Benchmark the notification fan-in PostgreSQL store (WPB-26288)";
  license = lib.meta.getLicenseFromSpdxId "AGPL-3.0-only";
  mainProgram = "fan-in-perf";
}
