# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, amqp
, asn1-types
, base
, bytestring
, cassandra-util
, containers
, crypton
, crypton-connection
, crypton-pem
, crypton-x509
, crypton-x509-store
, data-default
, errors
, exceptions
, gitignoreSource
, hasql
, hasql-pool
, hourglass
, hspec
, hspec-discover
, http-client
, http-client-tls
, http-types
, imports
, lib
, memory
, metrics-wai
, monad-control
, prometheus-client
, retry
, servant
, servant-client
, servant-client-core
, servant-openapi3
, servant-server
, string-conversions
, temporary
, text
, time
, tinylog
, tls
, transformers
, types-common
, unliftio
, uuid
, wai
}:
mkDerivation {
  pname = "extended";
  version = "0.1.0";
  src = gitignoreSource ./.;
  libraryHaskellDepends = [
    aeson
    amqp
    asn1-types
    base
    bytestring
    cassandra-util
    containers
    crypton
    crypton-connection
    crypton-x509
    crypton-x509-store
    data-default
    errors
    exceptions
    hasql
    hasql-pool
    http-client
    http-client-tls
    http-types
    imports
    memory
    metrics-wai
    monad-control
    prometheus-client
    retry
    servant
    servant-client
    servant-client-core
    servant-openapi3
    servant-server
    text
    time
    tinylog
    tls
    transformers
    types-common
    unliftio
    uuid
    wai
  ];
  testHaskellDepends = [
    aeson
    asn1-types
    base
    bytestring
    crypton
    crypton-pem
    crypton-x509
    hourglass
    hspec
    imports
    string-conversions
    temporary
  ];
  testToolDepends = [ hspec-discover ];
  description = "Extended versions of common modules";
  license = lib.licenses.agpl3Only;
}
