# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, amqp
, base
, bytestring
, cassandra-util
, containers
, crypton
, crypton-asn1-types
, crypton-connection
, crypton-pem
, crypton-x509
, crypton-x509-store
, data-default
, errors
, exceptions
, hasql
, hasql-resource-pool
, hspec
, hspec-discover
, http-client
, http-client-tls
, http-types
, imports
, lib
, megaparsec
, metrics-wai
, monad-control
, postgresql-connection-string
, prometheus-client
, QuickCheck
, ram
, retry
, servant
, servant-client
, servant-client-core
, servant-openapi3
, servant-server
, string-conversions
, temporary
, text
, time
, time-hourglass
, tinylog
, tls
, transformers
, types-common
, unliftio
, wai
}:
mkDerivation {
  pname = "extended";
  version = "0.1.0";
  src = ./.;
  libraryHaskellDepends = [
    aeson
    amqp
    base
    bytestring
    cassandra-util
    containers
    crypton
    crypton-asn1-types
    crypton-connection
    crypton-x509
    crypton-x509-store
    data-default
    errors
    exceptions
    hasql
    hasql-resource-pool
    http-client
    http-client-tls
    http-types
    imports
    megaparsec
    metrics-wai
    monad-control
    postgresql-connection-string
    prometheus-client
    ram
    retry
    servant
    servant-client
    servant-client-core
    servant-openapi3
    servant-server
    text
    time
    time-hourglass
    tinylog
    tls
    transformers
    types-common
    unliftio
    wai
  ];
  testHaskellDepends = [
    aeson
    base
    bytestring
    containers
    crypton
    crypton-asn1-types
    crypton-pem
    crypton-x509
    hspec
    imports
    postgresql-connection-string
    QuickCheck
    string-conversions
    temporary
    text
    time-hourglass
  ];
  testToolDepends = [ hspec-discover ];
  description = "Extended versions of common modules";
  license = lib.licenses.agpl3Only;
}
