# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, base
, bytestring
, gitignoreSource
, HsOpenSSL
, http-types
, http2-manager
, lib
, yaml
}:
mkDerivation {
  pname = "backend-notification-pusher";
  version = "0.1.0.0";
  src = gitignoreSource ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson
    base
    bytestring
    HsOpenSSL
    http-types
    http2-manager
    yaml
  ];
  description = "Pushes backend notifications to remote federated backends";
  license = lib.licenses.agpl3Only;
  mainProgram = "backend-notification-pusher";
}
