# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, amqp
, base
, bytestring
, gitignoreSource
, HsOpenSSL
, http-types
, http2-manager
, imports
, lib
, text
, types-common
, wire-api-federation
, yaml
}:
mkDerivation {
  pname = "backend-notification-pusher";
  version = "0.1.0.0";
  src = gitignoreSource ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson
    amqp
    base
    bytestring
    HsOpenSSL
    http-types
    http2-manager
    imports
    text
    types-common
    wire-api-federation
    yaml
  ];
  executableHaskellDepends = [ HsOpenSSL imports types-common ];
  testHaskellDepends = [ base imports ];
  description = "Pushes backend notifications to remote federated backends";
  license = lib.licenses.agpl3Only;
  mainProgram = "backend-notification-pusher";
}
