{{- if .Values.fakeS3.enabled }}
# We use a separate ingress for minio because we want to restrict access to /minio/ path
# for security reasons
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx-ingress-services.getMinioIngressName" . | quote }}
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location /minio/ {
        return 403;
      }
spec:
  ingressClassName: "{{ .Values.config.ingressClass }}"
  tls:
  - hosts:
      - {{ .Values.config.dns.fakeS3 }}
    secretName: {{ include "nginx-ingress-services.getCertificateSecretName" . | quote }}
  rules:
    - host: {{ .Values.config.dns.fakeS3 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.s3.serviceName }}
                port:
                  number: {{ .Values.service.s3.externalPort }}
{{- end }}
