apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-nginx-ingress-custom-headers
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  X-SSL-Certificate: $ssl_client_escaped_cert
