# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, base
, gitignoreSource
, imports
, lib
, openapi3
, QuickCheck
, tasty
, tasty-quickcheck
, wire-api
}:
mkDerivation {
  pname = "brig-types";
  version = "1.35.0";
  src = gitignoreSource ./.;
  libraryHaskellDepends = [ base wire-api ];
  testHaskellDepends = [
    aeson
    base
    imports
    openapi3
    QuickCheck
    tasty
    tasty-quickcheck
    wire-api
  ];
  description = "User Service";
  license = lib.licenses.agpl3Only;
}
