#!/usr/bin/env bash
set -euo pipefail

TEMP=$(mktemp --tmpdir swagger-XXX.json)

trap cleanup EXIT
cleanup() {
  rm -f $TEMP
}

curl http://localhost:8082/v7/api/swagger.json > $TEMP
vacuum lint $TEMP -a -d -w
