#!/usr/bin/env bash
set -euo pipefail

TEMP=$(mktemp --tmpdir swagger-XXX.json)

trap cleanup EXIT
cleanup() {
  rm -f $TEMP
}

curl http://localhost:8082/v7/api/swagger.json > $TEMP
docker run --rm -v $(dirname $TEMP):/work:ro dshanley/vacuum:v0.9.8 lint -a -e -d $(basename $TEMP)
