{{- $backgroundWorker := index .Values "background-worker" }}
apiVersion: v1
kind: Secret
metadata:
  name: background-worker
  labels:
    app: background-worker
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{/* for_helm_linting is necessary only since the 'with' block below does not throw an error upon an empty .Values.background-worker.secrets.*/}}
  for_helm_linting: {{ required "No .secrets found in configuration. Did you forget to helm <command> -f path/to/secrets.yaml ?" $backgroundWorker.secrets | quote | b64enc | quote }}

  {{- with $backgroundWorker.secrets }}
  {{- if .awsKeyId }}
  awsKeyId: {{ .awsKeyId | b64enc | quote }}
  awsSecretKey: {{ .awsSecretKey | b64enc | quote }}
  {{- end }}
  {{- if (not $backgroundWorker.config.useSES) }}
  smtp-password.txt: {{ .smtpPassword | b64enc | quote }}
  {{- end }}
  rabbitmqUsername: {{ .rabbitmq.username | b64enc | quote }}
  rabbitmqPassword: {{ .rabbitmq.password | b64enc | quote }}
  {{- end }}
