# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, aeson-pretty
, array
, base
, bytestring
, Cabal
, case-insensitive
, containers
, data-default
, directory
, filepath
, gitignoreSource
, http-client
, http-types
, imports
, lib
, network-uri
, random
, scientific
, tasty
, text
, transformers
}:
mkDerivation {
  pname = "integration";
  version = "0.1.0";
  src = gitignoreSource ./.;
  isLibrary = false;
  isExecutable = true;
  setupHaskellDepends = [ base Cabal containers directory filepath ];
  executableHaskellDepends = [
    aeson
    aeson-pretty
    array
    base
    bytestring
    case-insensitive
    data-default
    http-client
    http-types
    imports
    network-uri
    random
    scientific
    tasty
    text
    transformers
  ];
  license = lib.licenses.agpl3Only;
  mainProgram = "integration";
}
