apiVersion: v1
kind: ConfigMap
metadata:
  name: galley
data:
  {{- with .Values.galley.config }}
  galley.yaml: |
    logFormat: {{ .logFormat }}
    logLevel: {{ .logLevel }}
    logNetStrings: {{ .logNetStrings }}

    galley:
      host: 0.0.0.0
      port: 8080

    cassandra:
      endpoint:
        host: {{ .cassandra.host }}
        port: 9042
      keyspace: galley
      {{- if hasKey .cassandra "filterNodesByDatacentre" }}
      filterNodesByDatacentre: {{ .cassandra.filterNodesByDatacentre }}
      {{- end }}
      {{- if eq (include "useCassandraTLS" .cassandra) "true" }}
      tlsCa: /etc/wire/galley/cassandra/{{- (include "galley.tlsSecretRef" . | fromYaml).key }}
      {{- end }}

    postgresql: {{ toYaml .postgresql | nindent 6 }}
    postgresqlPool: {{ toYaml .postgresqlPool | nindent 6 }}
    {{- if hasKey $.Values.galley.secrets "pgPassword" }}
    postgresqlPassword: /etc/wire/galley/secrets/pgPassword
    {{- end }}

    brig:
      host: brig
      port: 8080

    gundeck:
      host: gundeck
      port: 8080

    spar:
      host: spar
      port: 8080

    {{- if $.Values.galley.config.enableFederation }}
    federator:
      host: federator
      port: 8080

    {{- with .rabbitmq }}
    rabbitmq:
      host: {{ .host }}
      port: {{ .port }}
      vHost: {{ .vHost }}
      enableTls: {{ .enableTls }}
      insecureSkipVerifyTls: {{ .insecureSkipVerifyTls }}
      {{- if .tlsCaSecretRef }}
      caCert: /etc/wire/galley/rabbitmq-ca/{{ .tlsCaSecretRef.key }}
      {{- end }}
    {{- end }}
    {{- end }}

    {{- if (.journal) }}
    journal:
      queueName: {{ .journal.queueName }}
      endpoint: {{ .journal.endpoint }}
    {{- end }}

    postgresMigration: {{- toYaml .postgresMigration | nindent 6 }}

    settings:
{{ include "wire-server.settings.common" .settings | indent 6 }}
  {{- end }}
