# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation, aeson, aeson-pretty, amqp, base, bytestring
, gitignoreSource, imports, lib, network, optparse-applicative
, text, types-common, wire-api, wire-api-federation
}:
mkDerivation {
  pname = "rabbitmq-consumer";
  version = "1.0.0";
  src = gitignoreSource ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson aeson-pretty amqp base bytestring imports network
    optparse-applicative text types-common wire-api wire-api-federation
  ];
  executableHaskellDepends = [ base ];
  description = "CLI tool to consume messages from a RabbitMQ queue";
  license = lib.licenses.agpl3Only;
  mainProgram = "rabbitmq-consumer";
}
