# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, attoparsec
, base
, bytestring
, bytestring-conversion
, containers
, gitignoreSource
, imports
, lens
, lib
, network-uri
, servant
, text
, types-common
, wire-api
}:
mkDerivation {
  pname = "gundeck-types";
  version = "1.45.0";
  src = gitignoreSource ./.;
  libraryHaskellDepends = [
    aeson
    attoparsec
    base
    bytestring
    bytestring-conversion
    containers
    imports
    lens
    network-uri
    servant
    text
    types-common
    wire-api
  ];
  license = lib.licenses.agpl3Only;
}
