# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation, aeson, base, bytestring, errors, gitignoreSource
, http-client, http-types, imports, iso3166-country-codes, lib
, text, time
}:
mkDerivation {
  pname = "ropes";
  version = "0.4.20";
  src = gitignoreSource ./.;
  libraryHaskellDepends = [
    aeson base bytestring errors http-client http-types imports
    iso3166-country-codes text time
  ];
  description = "Various ropes to tie together with external web services";
  license = lib.licenses.agpl3Only;
}
