# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, base
, bytestring
, gitignoreSource
, lib
, primitive
, text
}:
mkDerivation {
  pname = "memchr-test";
  version = "0.1.0";
  src = gitignoreSource ./.;
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [ base bytestring primitive text ];
  description = "Minimal test service for memchr";
  license = lib.licenses.agpl3Only;
  mainProgram = "memchr-test";
}
