# WARNING: GENERATED FILE, DO NOT EDIT.
# This file is generated by running hack/bin/generate-local-nix-packages.sh and
# must be regenerated whenever local packages are added or removed, or
# dependencies are added or removed.
{ mkDerivation
, aeson
, aeson-diff
, aeson-qq
, attoparsec
, attoparsec-aeson
, base
, bytestring
, case-insensitive
, containers
, email-validate
, gitignoreSource
, hashable
, hedgehog
, hspec
, hspec-discover
, hspec-expectations
, hspec-wai
, http-api-data
, http-media
, http-types
, HUnit
, hw-hspec-hedgehog
, imports
, indexed-traversable
, lens-aeson
, lib
, list-t
, microlens
, mmorph
, mtl
, network-uri
, QuickCheck
, retry
, scientific
, servant
, servant-client
, servant-client-core
, servant-server
, stm
, stm-containers
, string-conversions
, template-haskell
, text
, time
, utf8-string
, uuid
, vector
, wai
, wai-extra
, wai-utilities
, warp
}:
mkDerivation {
  pname = "hscim";
  version = "0.4.0.6";
  src = gitignoreSource ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson
    aeson-diff
    aeson-qq
    attoparsec
    attoparsec-aeson
    base
    bytestring
    case-insensitive
    containers
    email-validate
    hashable
    hspec
    hspec-expectations
    hspec-wai
    http-api-data
    http-media
    http-types
    imports
    list-t
    microlens
    mmorph
    mtl
    network-uri
    retry
    scientific
    servant
    servant-client
    servant-client-core
    servant-server
    stm
    stm-containers
    string-conversions
    template-haskell
    text
    time
    utf8-string
    uuid
    vector
    wai
    wai-extra
    wai-utilities
  ];
  executableHaskellDepends = [
    base
    email-validate
    network-uri
    stm
    stm-containers
    time
    warp
  ];
  testHaskellDepends = [
    aeson
    aeson-diff
    aeson-qq
    base
    bytestring
    case-insensitive
    email-validate
    hedgehog
    hspec
    hspec-expectations
    hspec-wai
    http-types
    HUnit
    hw-hspec-hedgehog
    imports
    indexed-traversable
    lens-aeson
    microlens
    network-uri
    QuickCheck
    scientific
    servant
    servant-server
    stm-containers
    text
    vector
    wai
    wai-extra
  ];
  testToolDepends = [ hspec-discover ];
  homepage = "https://github.com/wireapp/wire-server/blob/develop/libs/hscim/README.md";
  description = "hscim json schema and server implementation";
  license = lib.licenses.agpl3Only;
  mainProgram = "hscim-server";
}
