apiVersion: v1
description: mlsstats - Push Proteus to MLS statistics to S3
name: mlsstats
version: 0.0.1
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - name: mlsstats
      image: quay.io/wire/mlsstats:do-not-use
