apiVersion: v1
description: cassandra database schema migration for gundeck,brig,galley,spar
name: cassandra-migrations
version: 0.0.42
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - name: alpine
      image: docker.io/library/alpine:3.21.3
    - name: gundeck-schema
      image: "quay.io/wire/gundeck-schema:do-not-use"
    - name: brig-schema
      image: "quay.io/wire/brig-schema:do-not-use"
    - name: galley-schema
      image: "quay.io/wire/galley-schema:do-not-use"
    - name: spar-schema
      image: "quay.io/wire/spar-schema:do-not-use"
    - name: galley-migrate-data
      image: "quay.io/wire/galley-migrate-data:do-not-use"
    - name: gundeck-migrate-data
      image: "quay.io/wire/gundeck-migrate-data:do-not-use"
    - name: spar-migrate-data
      image: "quay.io/wire/spar-migrate-data:do-not-use"
