{{- if and .Values.cannon.service.nginz.enabled (not .Values.cannon.service.nginz.certManager.enabled ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cannon.service.nginz.tls.secretName }}
  labels:
    app: cannon-nginz
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.cannon.secrets.nginz.tls.crt | b64enc | quote }}
  tls.key: {{ .Values.cannon.secrets.nginz.tls.key | b64enc | quote }}
{{- end }}
